### ISSUE TITLE
Business Logic

### ISSUE THREAD

**Issue by Daquiver1** [Daquiver1/past_questions_bot#10]

**Comment by emilearthur** [comment]
@Daquiver1 kindly include the logic we discussed in the comment. Also, use draw.io to document the flow.

**Comment by Daquiver1** [comment]
Sure. Will do that.

**Comment by Daquiver1** [comment]
Draw.io link: https://drive.google.com/file/d/1qHO0Wt3kZTHvLXUVnGoxJMTXqem0BhSS/view?usp=sharing
